# Spring Application
spring.application.name=sentinel-load-engine
# Datasource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sentinel}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sentinel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sentinel}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
# Cassandra Data
spring.cassandra.contact-points=${SPRING_DATA_CASSANDRA_CONTACT_POINTS:localhost}
spring.cassandra.port=${SPRING_DATA_CASSANDRA_PORT:9042}
spring.cassandra.keyspace-name=${SPRING_DATA_CASSANDRA_KEYSPACE:sentinel}
spring.cassandra.username=${SPRING_DATA_CASSANDRA_USERNAME:cassandra}
spring.cassandra.password=${SPRING_DATA_CASSANDRA_PASSWORD:cassandra}
spring.cassandra.local-datacenter=${SPRING_DATA_CASSANDRA_DATACENTER:datacenter1}
# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
# Server
server.port=8083

# Admin
sentinel.admin.username=rishabhpndt19@gmail.com
sentinel.admin.password=Admin@123
sentinel.ingestion.url=http://localhost:8081/v1/ingest

# Show generated SQL
#spring.jpa.show-sql=true

# Format SQL for readability
#spring.jpa.properties.hibernate.format_sql=true

# Show bind parameter values
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
