global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: sentinel-ingest
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ingest:8081"]
        labels:
          app: ingest

  - job_name: sentinel-worker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["worker:8082"]
        labels:
          app: worker
