spring:
  application:
    name: sentinel-ingest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sentinel}
    username: ${SPRING_DATASOURCE_USERNAME:sentinel}
    password: ${SPRING_DATASOURCE_PASSWORD:sentinel}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: "1"
      properties:
        linger.ms: 20
        batch.size: 65536

sentinel:
  kafka:
    request-events-topic: sentinel.request-events
    request-events-partitions: 24
    request-events-replicas: 1

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
